# Generated by Django 6.0.3 on 2026-03-30 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default='general', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'purposes',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('agent_version', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=100)),
                ('fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='agents.purpose')),
            ],
            options={
                'db_table': 'agents',
            },
        ),
    ]
