# Generated by Django 6.0.3 on 2026-03-31 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSOUser',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('end_user', 'End User'), ('resolver', 'Resolver'), ('admin', 'Admin')], default='end_user', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_agents', models.JSONField(blank=True, default=list)),
                ('allowed_purposes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sso_users',
            },
        ),
        migrations.CreateModel(
            name='ResolverProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='_resolver_profile', serialize=False, to='auth_core.ssouser')),
                ('skill_set', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'resolver_profiles',
            },
        ),
    ]
