# Generated by Django 6.0.3 on 2026-03-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, db_index=True, help_text='Scope to a specific purpose/team. NULL = global default.', max_length=255, null=True)),
                ('applies_to', models.CharField(choices=[('ticket', 'Ticket'), ('alert', 'Alert'), ('both', 'Both')], db_index=True, default='both', max_length=10)),
                ('key', models.CharField(help_text="Value stored in the status field, e.g. 'OPEN'", max_length=50)),
                ('label', models.CharField(help_text="Human-readable display name, e.g. 'Open'", max_length=100)),
                ('color', models.CharField(blank=True, default='', help_text="Optional UI hint e.g. '#22c55e' or 'green'", max_length=20)),
                ('is_initial', models.BooleanField(default=False, help_text='Status assigned when a ticket/alert is first created.')),
                ('is_terminal', models.BooleanField(default=False, help_text="No further transitions expected. Treated as 'closed'.")),
                ('is_auto_resolvable', models.BooleanField(default=False, help_text='ResolutionService may auto-close items in this status.')),
                ('order', models.IntegerField(default=0, help_text='Display ordering within the same scope.')),
            ],
            options={
                'db_table': 'workflow_statuses',
                'ordering': ['purpose', 'applies_to', 'order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('purpose', 'key', 'applies_to'), name='uq_workflow_status_scope')],
            },
        ),
    ]
