# Generated by Django

from django.db import migrations


def seed_default_statuses(apps, schema_editor):
    WorkflowStatus = apps.get_model("workflows", "WorkflowStatus")

    # Global defaults (purpose=None) that apply to BOTH tickets and alerts.
    defaults = [
        # key, label, is_initial, is_terminal, is_auto_resolvable, order, color
        ("OPEN",   "Open",         True,  False, True,  10, "blue"),
        ("ACK",    "Acknowledged", False, False, True,  20, "yellow"),
        ("CLOSED", "Closed",       False, True,  False, 30, "gray"),
    ]

    for key, label, initial, terminal, auto_res, order, color in defaults:
        WorkflowStatus.objects.update_or_create(
            purpose=None,
            applies_to="both",
            key=key,
            defaults={
                "label": label,
                "is_initial": initial,
                "is_terminal": terminal,
                "is_auto_resolvable": auto_res,
                "order": order,
                "color": color,
            }
        )

def unseed_default_statuses(apps, schema_editor):
    WorkflowStatus = apps.get_model("workflows", "WorkflowStatus")
    WorkflowStatus.objects.filter(purpose__isnull=True, key__in=["OPEN", "ACK", "CLOSED"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_default_statuses, reverse_code=unseed_default_statuses),
    ]
