# Generated by Django 6.0.3 on 2026-03-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=255)),
                ('purpose', models.CharField(db_index=True, default='general', max_length=100)),
                ('priority', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], db_index=True, default='P4', max_length=5)),
                ('resolution_steps', models.JSONField(default=list)),
                ('resolver_notes', models.TextField(blank=True, null=True)),
                ('resolution_meta', models.JSONField(blank=True, default=dict, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'guidance',
                'constraints': [models.UniqueConstraint(fields=('metric_name', 'priority', 'purpose'), name='uq_guidance_metric_priority_purpose')],
            },
        ),
    ]
