# Generated by Django 6.0.3 on 2026-03-31 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevCredential',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dev_credential', serialize=False, to='auth_core.ssouser')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dev_credentials',
            },
        ),
    ]
