"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vdtuyr#l7kugd)3c5%enm-bvh!5@m!pw&d!^r$wcx0e$keln(o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'attachments',
    'auth_core',
    'agents',
    'tickets',
    'alerts',
    'guidance',
    'dev_auth',   # ⚠️  remove from INSTALLED_APPS in production
    'workflows',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # JWT auth — runs early so request.sso_user is available to all views
    'auth_core.middleware.JWTAuthMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ---------------------------------------------------------------------------
# JWT / SSO Auth settings
# ---------------------------------------------------------------------------
import os

# Secret used to validate incoming JWTs.
# For HS256 (symmetric): shared secret string.
# For RS256/ES256 (asymmetric / OIDC): set to the provider's PEM public key.
AUTH_JWT_SECRET    = os.environ.get('JWT_SECRET', 'dev-jwt-secret-change-in-production')

# Must match the algorithm the SSO provider uses to sign tokens.
# HS256 for simple shared-secret setups; RS256 for Okta / Auth0 / Keycloak / Google.
AUTH_JWT_ALGORITHM = os.environ.get('JWT_ALGORITHM', 'HS256')

# Optional — validate the `aud` claim.  Set to your client_id in production.
AUTH_JWT_AUDIENCE  = os.environ.get('JWT_AUDIENCE',  None)

# Optional — validate the `iss` claim.  Set to your provider's issuer URL.
AUTH_JWT_ISSUER    = os.environ.get('JWT_ISSUER',    None)

# dev_auth: JWT lifetime for tokens issued by the local demo auth server.
# Ignored in production (dev_auth endpoints are blocked when DEBUG=False).
DEV_AUTH_TOKEN_TTL_HOURS = int(os.environ.get('DEV_AUTH_TOKEN_TTL_HOURS', 24))
