# Generated by Django 6.0.3 on 2026-03-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=255)),
                ('severity', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], db_index=True, max_length=10)),
                ('purpose', models.CharField(db_index=True, default='general', max_length=255)),
                ('type', models.CharField(choices=[('SINGLE', 'Single'), ('GROUP', 'Group')], default='SINGLE', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACK', 'Acknowledged'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('agent_ids', models.TextField(default='[]')),
                ('total_occurrence', models.IntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-last_seen_at'],
                'constraints': [models.UniqueConstraint(fields=('metric_name', 'severity', 'purpose', 'status'), name='uq_alert_metric_severity_purpose_status')],
            },
        ),
    ]
