# Generated by Django 6.0.3 on 2026-03-31 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attachment',
            new_name='attachments_content_7c0e26_idx',
            old_name='attachments_content_obj_idx',
        ),
        migrations.RenameIndex(
            model_name='attachment',
            new_name='attachments_kind_57dccb_idx',
            old_name='attachments_kind_idx',
        ),
    ]
