# Generated by Django 6.0.3 on 2026-03-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=255)),
                ('metric_name', models.CharField(db_index=True, max_length=255)),
                ('severity', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], max_length=10)),
                ('purpose', models.CharField(db_index=True, default='general', max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACK', 'Acknowledged'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('detectors', models.TextField(default='[]')),
                ('meta', models.TextField(blank=True, default='{}')),
                ('message', models.TextField(blank=True, default='')),
                ('occurrence_count', models.IntegerField(default=1)),
                ('first_occurred_at', models.DateTimeField()),
                ('last_occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-last_occurred_at'],
            },
        ),
    ]
